export const products = [
  {
    id: 1,
    produkt: "Aperol",
    typ: "Likér",
    objem: "0,7l",
    obsah: "11%",
    cena: 19,
    krajina: "Taliansko",
    popis:
      "Aperol je alkoholický nápoj radiaci sa medzi korenené bittery. Má oranžovo-červenú farbu s ovocnou ľahkou horkou chuťou. Vyrába sa z horca, rebarbory, výťažkov z pomarančov, aromatických bylín a farbív. Vznikol v talianskej rodinnej firme Barbieri na kraji mesta Padova okolo roku 1919. Jeho zvláštnosťou je veľmi nízky obsah alkoholu.",
  },
  {
    id: 2,
    produkt: "A.H. Riise: Non Plus Ultra",
    typ: "Rum",
    objem: "0,7l",
    obsah: "42%",
    cena: 90,
    krajina: "Americké Panenské Ostrovy",
    popis:
      "A.H. Riise: Non Plus Ultra je luxusným „ultra premium rumom, ktorý dopĺňa našu radu rumov A.H. Riise. Pojem 'Non Plus Ultra' pochádza z herkulových stĺpov z rímskej mytológie, ktoré sa postavili blízko Gibraltárskej úžiny a označovali hranice známeho sveta. Stĺpy mali nápis 'Non Plus Ultra' (latinsky), čo znamená (Nič nie ja ďalej ani ponad) ako varovanie pre moreplavcov, aby nepokračovali do neznámeho sveta. Tento rum má špeciálnu česť nosiť meno 'Non Plus Ultra', čo sa dá voľne preložiť ako „najlepší alebo „nič po tomto, keďže je to najlepší a najstarší rum, ktorý máme k dispozícii. Non Plus Ultra ručne mieša náš „majster pre destiláciu, ktorý osobne vyberá každý súdok používaný pre konečnú zmes rumu. Tento rum má nádhernú tmavú mahagónovú farbu s elegantným korenistým bukétom s tónmi melasy, duba, tabaku a pomaranča.Chuť Non Plus Ultra je jedinečnou skúsenosťou s veľmi bohatou, dlhou a ovocnou chuťou s náznakmi cédrového dreva, vanilky, karamelu, jemného sherry a sevillských pomarančov, čo pokračuje takmer nekonečne a končí sa elegantným jemným finišom.",
  },
  {
    id: 3,
    produkt: "Bacardí Carta Blanca",
    typ: "Rum",
    objem: "0,7l",
    obsah: "37,50%",
    cena: 18,
    krajina: "Portoriko",
    popis:
      "Bacardí Carta Blanca. Najpredávanejšia značka liehovín po celom svete sa tešísvojej popularite vo viac ako 170 krajinách sveta. Bacardi Carta Blanca bolazaložená v roku 1862 a je stále pozoruhodnou rodinnou značkou. Aróma: veľmisvieža, s poznámkami citróna a nádychom hrušky Chuť: čistá a svieža, s príjemnoucitrusovou príchuťou, veľmi hladká, nie príliš ostrá dochuť alkoholu. Záver: čistýa jemný",
  },
  {
    id: 4,
    produkt: "Ballantines: Ballantine’s Finest",
    typ: "Whiskey",
    objem: "0,7l",
    obsah: "40%",
    cena: 18,
    krajina: "Škótsko",
    popis:
      "Ballantines: Ballantine’s Finest. Jemná a elegantná miešaná škótska whisky. Jejsvetlozlatá farba a nezameniteľná chuť pochádzajú z komplexnej zmesi viac ako 40sladových whisky, z ktorých všetky zreli najmenej tri roky. Odborník Jim Murraytúto whisky vo svojej „Biblii“ v roku 2015 vyhlásil za absolútneho víťaza vkategórii blends.",
  },
  {
    id: 5,
    produkt: "Beefeater",
    typ: "Gin",
    objem: "0,7l",
    obsah: "40%",
    cena: 21,
    krajina: "Anglicko",
    popis:
      "Beefeater: Najoceňovanejší prémiový gin na svete. Beefeater je jediný gin, ktorý savyrába priamo v Londýne, čo z neho robí už desaťročia pravého britskéhogentlemana, ktorý po celom svete hrdo a patrične reprezentuje svoje rodisko.Beefeater je oviežujúci, čistý a zároveň ostrý gin s nepatrným nádychom citrusov aovocia, vyváženým chuťou korenia. Je výborným základom pre rôzne koktaily.Beefeater Gin je číslo jeden spomedzi prémiových ginov sveta a ročne sa ho predáviac ako 21 miliónov litrov.",
  },
  {
    id: 6,
    produkt: "Beefeater",
    typ: "Gin",
    objem: "1l",
    obsah: "40%",
    cena: 25,
    krajina: "Anglicko",
    popis:
      "Beefeater: Najoceňovanejší prémiový gin na svete. Beefeater je jediný gin, ktorý savyrába priamo v Londýne, čo z neho robí už desaťročia pravého britskéhogentlemana, ktorý po celom svete hrdo a patrične reprezentuje svoje rodisko.Beefeater je oviežujúci, čistý a zároveň ostrý gin s nepatrným nádychom citrusov aovocia, vyváženým chuťou korenia. Je výborným základom pre rôzne koktaily.Beefeater Gin je číslo jeden spomedzi prémiových ginov sveta a ročne sa ho predáviac ako 21 miliónov litrov.",
  },
  {
    id: 7,
    produkt: "Beefeater Pink",
    typ: "Gin",
    objem: "0,7l",
    obsah: "37,50%",
    cena: 22,
    krajina: "Anglicko",
    popis:
      "Beefeater: Najoceňovanejší prémiový gin na svete. Beefeater je jediný gin, ktorý savyrába priamo v Londýne, čo z neho robí už desaťročia pravého britskéhogentlemana, ktorý po celom svete hrdo a patrične reprezentuje svoje rodisko.Beefeater je oviežujúci, čistý a zároveň ostrý gin s nepatrným nádychom citrusov aovocia, vyváženým chuťou korenia. Je výborným základom pre rôzne koktaily.Beefeater Gin je číslo jeden spomedzi prémiových ginov sveta a ročne sa ho predáviac ako 21 miliónov litrov.",
  },
  {
    id: 8,
    produkt: "Becherovka",
    typ: "Likér",
    objem: "1l",
    obsah: "38%",
    cena: 18,
    krajina: "Česká republika",
    popis:
      "Becherovka: Becherovka je lahodný, tradičný a vysoko kvalitný bylinný likér. Tátoobľúbená česká klasika má svoje mimoriadne miesto pri všetkých míľnikoch vášhoživota. Je to 100% prírodný produkt bez akýchkoľvek chemických konzervačnýchlátok, umelých prímesí alebo emulgátorov. Becherovka sa vyrába z karlovarskejvody, vysoko kvalitného liehu, prírodného cukru a vybranej zmesy byliniek aprísad, ktoré jej dodávajú prirodzenú harmóniu. Becherovka má prírodnú a bohatúchuť, ktorú si môžete vychutnať najlepšie namrazenú alebo namiešanú v niektoromz vašich obľúbených koktailov.",
  },
  {
    id: 9,
    produkt: "Spišská Borovička",
    typ: "Destiláty",
    objem: "0,7l",
    obsah: "40%",
    cena: 13,
    krajina: "Slovensko",
    popis:
      "Spišská Borovička: Tradičná a pritom exkluzívna značková liehovina,základom ktorej je kvalitný prírodný borovičkový destilát. Svojou typickou chuťoua arómou po borievkach, ktorú ešte zvýrazňuje vetvička jalovca v každej fľaši, sitáto liehovina získala svojich stálych obdivovateľov.",
  },
  {
    id: 10,
    produkt: "Capt. Morgan Spiced Gold ",
    typ: "Rum",
    objem: "0,7l",
    obsah: "35%",
    cena: 17,
    krajina: "Portoriko",
    popis:
      "Captain Morgan: Captain Morgan Spiced Gold je unikátna liehovina sneopakovateľnou chuťou. Zreje celý rok v dubových sudoch, kde je obohacovanýunikátnou tajnou zmesou bylín a korenia.",
  },
  {
    id: 11,
    produkt: "Captain Morgan Spiced Gold ",
    typ: "Rum",
    objem: "1l",
    obsah: "35%",
    cena: 22,
    krajina: "Portoriko",
    popis:
      "Captain Morgan: Captain Morgan Spiced Gold je unikátna liehovina sneopakovateľnou chuťou. Zreje celý rok v dubových sudoch, kde je obohacovanýunikátnou tajnou zmesou bylín a korenia.",
  },
  {
    id: 12,
    produkt: "Dictador 12 YO",
    typ: "Rum",
    objem: "0,7l",
    obsah: "40%",
    cena: 38,
    krajina: "Kolumbia",
    popis:
      "Dictador 12 YO: Tento lahodný rum značky Dictador, zrejúci systémom Solera, savyrába v Kolumbii. Dozrieva medzi 8 až 14 rokom, s priemerným vekom zrenia 12rokov. Rum sa riedi na silu fľaše demineralizovanou vodou, ktorá sa pridáva pokvapkách po dobu 28 dní. Vôňa: Čerstvo pražené kávové zrná, krémová vanilka,karamel a med Manuka. Chuť: Známky po mede Manuka tvoria jadro chute, s tónminového korenia, zadymeného duba a vanilky. Záver: Krémové dozvuky s nádychomposoleného karamelu.",
  },
  {
    id: 13,
    produkt: "Diplomatico 12 YO",
    typ: "Rum",
    objem: "0,7l",
    obsah: "40%",
    cena: 40,
    krajina: "Venezuela",
    popis:
      "Diplomatico 12 YO: Diplomático Reserva Exclusiva je znamenitá zmes rumovdestilovaných kotlíkovou metódou. Tento proces sa uskutočňuje v špeciálnychmedených destilačných strojoch, ktoré sú uspôsobené len na plnenie obmedzenéhomnožstva. Reserva Exclusiva pomaly zreje v dubových sudoch na úpätí Ánd až 12rokov. Diplomático v sebe spája tie najvyberanejšie rezervy venezuelských rumov,ktoré vedia oceniť skutoční odborníci, ako aj tí, ktorí s rumom iba začínajú. Jehounikátne zloženie poukazuje na jedinečnú komplexnosť extrahovanú z destilačnéhoprocesu medu z cukrovej trstiny.Vzhľad: Tmavá, medená, až bronzová farba, ktorá vás na prvý pohľad môžepomýliť a budete si myslieť, že ide o vyzretý koňak alebo bourbon, samozrejme dochvíle, kým ucítite nádherný buket. Rum je číry a nemá v sebe žiadne sedimenty. Pridegustačnom rozvírení Diplomático zanechá na poháriku dlhé nožičky.Vôňa: Po ovoňaní vás zasiahne očarujúca aróma karamelizovanej melasy, tmavéhokandizovaného ovocia, škorice, vanilky a jemného korenia. Ak máme povedaťpravdu, človek sa po nadýchnutí chce ihneď napiť a ponoriť sa do tohto rumuplnými dúškami.Chuť: Vyvážená, v ústach nie veľmi ťažká. Mierne korenistá, s nádychommaslových keksíkov, vanilky, zrelého ovocia a tónmi karamelu a tabaku.Zakončenie je dlhé, suché a pomerne výrazne ucítite oriešky.",
  },
  {
    id: 14,
    produkt: "Dos Maderas 5 + 5",
    typ: "Rum",
    objem: "0,7l",
    obsah: "40%",
    cena: 38,
    krajina: "Barbados",
    popis:
      "Dos Maderas: Dos Maderas 5 + 5 je rum s pôvodom z Barbadosu a Guyany, kdezreje 5 rokov a následne je prepravený do Španielska, kde zreje ďaľších 5 rokov vsudoch po sladkom Sherry z odrody Pedro Ximenez, ktoré tam pobudlo až 20 rokov.Karibské podnebie a pivnice Williams &amp; Hubert vycibrili tento rum k dokonalosti.Má harmonickú vôňu s náznakom hrozienok, fíg, vanilky a čokolády.Chuť je veľmi jemná, komplexná a hrejivá. Skvelý digestív a alternatíva koňakovalebo brandy. Vhodný ku kvalitnej cigare.Farba: Tmavo-červená, až rubínová.Aróma: Sladkosť, karamel, tóny vanilky, škorice, muškátového orieška a praženéhoovocia.Chuť: Pomerne sladký vstup s náznakom sherry, chuť je plná, ale veľmi jemná. Ucítite aj karamel, čokoládu, tabakové listy, kožu a med. Zakončenie: Dlhé, jemné zakončenie s náznakmi sudov po sherry Pedro Ximenez.",
  },
  {
    id: 15,
    produkt: "Fernet stock: Fernet Stock ",
    typ: "Likér",
    objem: "0,5l",
    obsah: "38%",
    cena: 11,
    krajina: "Česká republika",
    popis:
      "Fernet stock: Fernet Stock - výnimočne dobrý a výnimočne horký bylinný likér,ktorý je obľúbenou liehovinou v Slovenskej republike. Jeho vznik sa datuje rokom1927. Práve vtedy totiž taliansky podnikateľ Lionello Stock začal vo svojej likérke vPlzni -Božkove vyrábať horký Fernet Stock. Receptúra výroby je samozrejme prísnetajná, ale základnými surovinami pre výrobu Fernetu Stock sú bylinky dovážanépredovšetkým zo Stredomoria a Álp.",
  },
  {
    id: 16,
    produkt: "Fernet stock Citrus",
    typ: "Likér",
    objem: "0,5l",
    obsah: "27%",
    cena: 11,
    krajina: "Česká republika",
    popis:
      "Fernet stock citrus: Ako už názov napovedá, základom Fernetu Stock Citrus jeklasický Fernet Stock. Na rozdiel od neho je však Fernet Stock Citrus sladší a mánižší obsah alkoholu. Neopakovateľná kombinácia štrnástich byliniek z celéhosveta, najjemnejšieho liehu, kvalitnej vody a karamelového kuléru, je naviacdoplnená prírodnými arómami vybraných citrusových plodov najvyššej kvality.Fernet Stock Citrus je vynikajúci predovšetkým v kombinácii s ľadom, ale hodí sa ipre prípravu nepreberného množstva miešaných nápojov.",
  },
  {
    id: 17,
    produkt: "Finlandia",
    typ: "Vodka",
    objem: "0,7l",
    obsah: "40%",
    cena: 17,
    krajina: "Fínsko",
    popis:
      "Finlandia: Finlandia vodka je čistá a dokonalá jediná prémiova vodka na svete,vyrobená z prírodnej filtrovanej ľadovcovej vody a šesťradého jačmeňa, dokonalevyzretého v arktickom lete. Používané suroviny nesmú byť vyrábané inde než voFínsku. Je mrazivo priezračná, zamatovo čistá, je vytvorená pre výnimočné chvíle.",
  },
  {
    id: 18,
    produkt: "Finlandia Cranberry",
    typ: "Vodka",
    objem: "1l",
    obsah: "37,50%",
    cena: 22,
    krajina: "Fínsko",
    popis:
      "Finlandia Cranberry: Finlandia Cranberry Fusion je jedinečne hladká vodka, slahodnou chuťou a arómou čerstvých brusníc.",
  },
  {
    id: 19,
    produkt: "Bombay",
    typ: "Gin",
    objem: "0,7l",
    obsah: "40%",
    cena: 25,
    krajina: "Anglicko",
    popis:
      "Bombay: Bombay Sapphire je destilovaný úplne unikátnym procesom, aký sa užívauž len v štyroch výrobniach na svete. Na rozdiel od ostatných ginov, ktoré súdestilované spoločne s bylinkovými ingredienciami, Bombay Sapphire jedestilovaný čistý bez prímesí. Aby získal svoju unikátnu chuť a vôňu, liehovinaprechádza zjednodušene povedané 'bylinkovou parou'. Tento postup umožňuje, ževšetky arómy sú plne absorbované. Výsledkom je úplná chuťová senzácia.Vôňa a chuť: ľahká a borievková, s jemným korenistým zahriatím. Súbežne sarozvíja jemná sladkosť mandľového cukru, aromatickosť angeliky a množstvobyliniek.",
  },
  {
    id: 21,
    produkt: "Cubical Premium London Dry gin",
    typ: "Gin",
    objem: "0,7l",
    obsah: "40%",
    cena: 33,
    krajina: "Španielsko",
    popis:
      "Cubical Premium London Dry gin: Cubical Premium London Dry Gin obsahujerastliny ako borievka, mandarínka, tymián, kamilka, mäta, aníz, mango, sladkýpomaranč, mandle, koriander, škorica, citrón, kardamóm a Budhova ruka, čo je typcitrusového ovocia. Je svieži a energický. V popredí sú ovocné tóny. Ako súčasťtradičného ginu a toniku je veľmi elegantný, aromatický a trvalý.",
  },
  {
    id: 22,
    produkt: "Cubical Ultra Premium",
    typ: "Gin",
    objem: "0,7l",
    obsah: "45%",
    cena: 42,
    krajina: "Španielsko",
    popis:
      "Cubical Ultra Premium: Botanic Ultra Premium London Dry Gin vyrába výrobcavín William &amp; Humbert s väčšou silou než ich štandardný Premium London DryGin. Vyrába sa z viacerých neobvyklých rastlín, vrátane mandarínky, mandlí aBudhovej ruky, čo je typ citrusového ovocia.",
  },
  {
    id: 23,
    produkt: "Cubical kiss",
    typ: "Gin",
    objem: "0,7l",
    obsah: "37,50%",
    cena: 33,
    krajina: "Španielsko",
    popis:
      "Cubical kiss: Gin Cubical Kiss, ktorý sa pôvodne nazýval Botanic Kiss, bol vydanýna španielsky trh, no destiluje sa v britskom liehovare Langleys. Hlavnou prísadouginu je tzv. Budhova ruka (ide o aromatické, chutné, ázijské citrusové ovocie).Ďalšími prísadami ginu sú napríklad borievka, koriander, angelika, pomarančovášupka, kosatec, sladké drievko, kasia a mandle. Používajú sa tu aj jahody, maliny ačučoriedky, ktoré tomuto ginu dodávajú peknú farbu.",
  },
  {
    id: 24,
    produkt: "Hennessy",
    typ: "Koňak",
    objem: "0,7l",
    obsah: "40%",
    cena: 37,
    krajina: "Francúzsko",
    popis:
      "Hennessy: Koňak Hennessy Very Special vzniká zmiešaním 40 eaux-de-vie. Jehofarba je krásne jasná a zlatistá. Silnému buketu dominujú dubové tóny, ktorénásledne odznievajú a odhaľujú vôňu lieskových orieškov. V chuti je skombinovanásladkosť červeného bobuľového ovocia s náznakom vanilky.",
  },
  {
    id: 25,
    produkt: "Hruška Spiš Originál",
    typ: "Destiláty",
    objem: "0,7l",
    obsah: "40%",
    cena: 15,
    krajina: "Slovensko",
    popis:
      "Hruška Spiš Originál: V tomto výrobku nájde spotrebiteľ presne to, čo dáva tušiť užjeho názov - lahodnú chuť zrelých hrušiek, vytvorenú výhradne z prírodnýchzložiek, či už je to ovocný destilát, prírodná hrušková aróma, alebo samotný kúsokzrelej hrušky. Jej nepochybne skvelá chuť a vôňa je afrodiziakom pre telo i dušunáročných požívateľov.",
  },
  {
    id: 26,
    produkt: "Jack Daniels Apple",
    typ: "Whiskey",
    objem: "0,7l",
    obsah: "35%",
    cena: 29,
    krajina: "USA",
    popis:
      "Jack Daniels Apple: Jack Daniels Tennessee Apple má unikátny charakter JackDaniels-u Tennessee Whiskey, chuť chrumkavých zelených jabĺk a vynikajúci záver. Jeff Arnett túto whisky opísal ako 'čerstvo odtrhnuté jablko v pohári whiskyJack Daniels'. Chuť: čerstvé jablká kombinované s teplým karamelom a sklasickým korením.",
  },
  {
    id: 27,
    produkt: "Jack Daniels Honey",
    typ: "Whiskey",
    objem: "0,7l",
    obsah: "35%",
    cena: 29,
    krajina: "USA",
    popis:
      "Jack Daniels Honey: Nestáva sa často, aby ľudia z liehovaru Jack Daniel´s pridali do rodiny svojich produktov niečo nové. Keď sa tak stane, môžete rátať s tým, žeide o výnimočnú kvalitu. Vychutnajte si Tennessy Honey na množstvo spôsobov a objavte jej delikátnu chuť s nádychom melasy, čokolády a praliniek. V aróme ucítite bohatý tón prírodnéhomedu, sladkej melasy a pražených orieškov. Záver tvorí jemná chuť s dlhou bohatoustopou medu a s orieškovým tónom.",
  },
  {
    id: 28,
    produkt: "Jack Daniels",
    typ: "Whiskey",
    objem: "0,7l",
    obsah: "40%",
    cena: 29,
    krajina: "USA",
    popis:
      "Jack Daniels: Whisky sa vyrába v Lynchburgu , v štáte Tennessee už od roku 1860. K výrobe sa používa čistá voda z vápencových jaskýň. Whisky je podobnábourbonu. Iná je v tom, že sa filtruje cez javorové uhlie vo veľkých drevenýchkadiach ešte pred starnutím. Dozrieva v nových dubových sudoch. Vôňa je veľmi vyzretá, raž dym, sladké drievko, karamel, med.Chuť stredne plná, raž, karamel, korenistá dochuť. Považuje sa za kultovú whisky.",
  },
  {
    id: 29,
    produkt: "Jack Daniels",
    typ: "Whiskey",
    objem: "1l",
    obsah: "40%",
    cena: 35,
    krajina: "USA",
    popis:
      "Jack Daniels: Whisky sa vyrába v Lynchburgu , v štáte Tennessee už od roku 1860.K výrobe sa používa čistá voda z vápencových jaskýň. Whisky je podobnábourbonu. Iná je v tom, že sa filtruje cez javorové uhlie vo veľkých drevenýchkadiach ešte pred starnutím. Dozrieva v nových dubových sudoch. Vôňa je veľmivyzretá, raž dym, sladké drievko, karamel, med. Chuť stredne plná, raž, karamel,korenistá dochuť. Považuje sa za kultovú whisky.",
  },
  {
    id: 30,
    produkt: "Jägermeister",
    typ: "Likér",
    objem: "0,7l",
    obsah: "35%",
    cena: 20,
    krajina: "Nemecko",
    popis:
      "Jagermaster: Jägermeister - bylinný likér so silnou, výraznou vôňou, citlivovyváženou horko sladkou chuťou a príslovečne priaznivými účinkami na tráviacusústavu. Vyrába sa podľa tajnej pôvodnej receptúry maceráciou 56 druhovkorienkov, bylín a ďalších prírodných zdrojov (okrem iného citrusovej kôry, anízu,sladkého drievka, šafranu, zázvoru a plodov borievky) v neutrálnom liehu počasšiestich týždňov. Zreje najmenej 1 rok leží v dubových sudoch.",
  },
  {
    id: 31,
    produkt: "Jameson",
    typ: "Whiskey",
    objem: "0,7l",
    obsah: "40%",
    cena: 23,
    krajina: "Írsko",
    popis:
      "Jameson Všetko sa začalo v roku 1780, kedy John Jameson kúpil liehovar nadublinskej Bow Street a začal vyrábať svoju neobvykle jemnú írsku whiskey. Avedel ju robiť naozaj dobre… Oddane pokračujeme v jeho tradícii aj dnes a starámesa o to, aby bola Jameson Irish Whiskey zakaždým taká skvelá, aká bola vtedy, keďJohn predal celkom prvý súdok. Je trikrát destilovaná, s dokonale vyváženou chuťoukorení, orechov a vanilky s podtextom zrelého ovocia, a vždy hodvábne jemná.Vôňa je ľahká, kvetinová, podčiarknutá korenistou arómou dreva a decentnoumedovou sladkosťou.",
  },
  {
    id: 32,
    produkt: "Jack Gentleman",
    typ: "Whiskey",
    objem: "0,7l",
    obsah: "40%",
    cena: 35,
    krajina: "USA",
    popis:
      "Jack Gentleman: Ako jediná na svete je táto whisky 2x prekvapkávaná cez drevenéuhlie. Je veľmi jemná, s výraznou chuťou pripomínajúcou exkluzívny koňak. Farbaje svetlá medovinová, s iskrou. Vôňa je jemná, uhladená, s vyrovnanou vôňousladkých pomarančov a podtónom čerstvej mäty. Môžeme cítiť jemnú arómukaramelu a škorice. Chuťovo pripomína jemne sladkastú mätu a zrelé jablká (spodtónom pečených jabĺk). Záver chuti je zo začiatku sladkastý a postupneprechádza do jablkovej.",
  },
  {
    id: 33,
    produkt: "Tatranský čaj",
    typ: "Likér",
    objem: "0,7l",
    obsah: "52%",
    cena: 21,
    krajina: "Slovensko",
    popis:
      "Tatranský čaj 52: Prírodný, originálny, čajovo – bylinný likér tvorený vyváženýmpomerom liehu, extraktov z bylín, čajov, ovocných výťažkov a destilátov, cukru avody. Je obohatený o extrakty výraznej šípky, ktorá vám pripomenie pohodujesenných večerov pri šálke šípkového čaju. Tento výnimočne sladkokyslý čaj jedoplnený o extrakty z rakytníka, ktoré sú dôvodom jeho sviežosti.",
  },
  {
    id: 34,
    produkt: "Presidente Marti 23y",
    typ: "Rum",
    objem: "0,7l",
    obsah: "40%",
    cena: 50,
    krajina: "Dominikánska republika",
    popis:
      "Presidente Marti 23y: Čo sa týka kubánskej línie, aj tento rum má názov, ktorý mákorene v kubánskej rodine Oliverovcov. José Julián Martí Pérez bol politik, spisovateľ a vodca hnutia za kubánsku nezávislosti v polovici devätnásteho storočia.Dnes je na Kube považovaný za jedného z najväčších národných hrdinov. Holdtomuto hrdinovi prichádza v podobe rumu, ktorý zreje vo francúzskych aamerických dubových sudoch tradičnou metódou solera. Kombinácia rumovrôzneho veku dáva rumu Presidente Marti 23 jemnosť a hĺbku. Vynikajúci vkombinácii s kubánskou cigarou! Aróma: ľahká, sladkastá, vanilková s čokoládouChuť: plná a komplexná, sladkasté ovocné tóny kombinované s tónmi červenéhoovocia, horkej čokolády a vanilkyZáver: teplý a dlhý",
  },
  {
    id: 35,
    produkt: "Slivka Spiš Originál",
    typ: "Destiláty",
    objem: "0,7l",
    obsah: "40%",
    cena: 15,
    krajina: "Slovensko",
    popis:
      "Slivka Spiš: Originálny produkt na báze slivkového destilátu a extraktu, ktoré spolus výlučne prírodnou arómou vytvárajú novú prekvapivú kompozíciu, chuťou avôňou pripomínajúcu starý známy slivkový kompót našich babičiek. Celkovýbuquet nápoja je zavŕšený plodom sušenej slivky, ktorý mu vtláča punc svojráznostia výnimočnosti.",
  },
  {
    id: 36,
    produkt: "Tequilla Olmeca: gold",
    typ: "Tequilla",
    objem: "0,7l",
    obsah: "38%",
    cena: 23,
    krajina: "Mexiko",
    popis:
      "Tequilla Olmeca Gold: Nádherná priezračná tequila vyrobená zo špičkovej modrej agávy a špeciálnym procesom, ktorý zdôrazňuje jej výnimočnú čistotu. Čistá najlepšie chutís citrónom a soľou, no je skvelá i na prípravu obľúbených drinkov ako TequilaSunrise alebo Margarita.",
  },
  {
    id: 37,
    produkt: "Tullamore dew",
    typ: "Whiskey",
    objem: "0,7l",
    obsah: "40%",
    cena: 21,
    krajina: "Írsko",
    popis:
      "Tullamore dew: Tullamore D.E.W. – Originálna írska blended whisky známa pocelom svete vďaka svojej jemnosti a komplexnosti. Túto unikátnu jemnosť zaistítrojitá destilácia a následné zrenie v sudoch po bourbone a po sherry po dobuminimálne troch rokov. Svoju jedinečnú komplexnosť získava vďaka zmiešaniuvšetkých troch druhov írskej whisky (pot still, grain, malt). Názov je odvodený ziniciálok prvého vlastníka, Daniela E. Williamsa – DEW.",
  },
  {
    id: 38,
    produkt: "Tullamore dew",
    typ: "Whiskey",
    objem: "1l",
    obsah: "40%",
    cena: 26,
    krajina: "Írsko",
    popis:
      "Tullamore dew: Tullamore D.E.W. – Originálna írska blended whisky známa pocelom svete vďaka svojej jemnosti a komplexnosti. Túto unikátnu jemnosť zaistítrojitá destilácia a následné zrenie v sudoch po bourbone a po sherry po dobuminimálne troch rokov. Svoju jedinečnú komplexnosť získava vďaka zmiešaniuvšetkých troch druhov írskej whisky (pot still, grain, malt). Názov je odvodený ziniciálok prvého vlastníka, Daniela E. Williamsa – DEW.",
  },
  {
    id: 39,
    produkt: "Nicolaus vodka",
    typ: "Vodka",
    objem: "1l",
    obsah: "38%",
    cena: 15,
    krajina: "Slovensko",
    popis:
      "Nicolaus: Unikátna jemnosť Nicolaus Extra Jemnej Vodky je ukrytá v krištáľovočistej tatranskej vode, viacnásobnej filtrácii cez strieborné filtre a 140 ročnej tradícii. Veľmi jemný lieh je pripravený najmodernejšími technológiami z vysokokvalitnéh oobilia.",
  },
  {
    id: 40,
    produkt: "Captain Morgan 35% + Coca Cola",
    typ: "Párty sety",
    objem: "0.7l + 1.75l",
    obsah: "35%",
    cena: 18,
    krajina: "",
    popis:
      "Captain Morgan Spiced Gold je unikátna liehovina sneopakovateľnou chuťou. Zreje celý rok v dubových sudoch, kde je obohacovanýunikátnou tajnou zmesou bylín a korenia. Coca-Cola je osviežujúci nealkoholický nápoj, ktorý prináša okamžiky pohody a radosti viac ako 125 rokov.",
  },
  {
    id: 41,
    produkt: "Beefeater Gin 40% + Kinley Tonic",
    typ: "Párty sety",
    objem: "0.7l + 1.5l",
    obsah: "40%",
    cena: 22,
    krajina: "",
    popis:
      "Najoceňovanejší prémiový gin na svete. Beefeater je jediný gin, ktorý savyrába priamo v Londýne, čo z neho robí už desaťročia pravého britskéhogentlemana, ktorý po celom svete hrdo a patrične reprezentuje svoje rodisko.Beefeater je oviežujúci, čistý a zároveň ostrý gin s nepatrným nádychom citrusov aovocia, vyváženým chuťou korenia. Je výborným základom pre rôzne koktaily.Beefeater Gin je číslo jeden spomedzi prémiových ginov sveta a ročne sa ho predáviac ako 21 miliónov litrov. Charakter nápojov Kinley presahuje hranice krajiny a kultúry. Vďaka nemu zažiješ radosť z objavovania bez ohľadu na to, na akú cestu sa vydáš. Každý dúšok je jedinečný ako ty. Na zdravie!",
  },
  {
    id: 42,
    produkt: "Finlandia Vodka 40% + 4x Red-Bull",
    typ: "Párty sety",
    objem: "0.7l",
    obsah: "40%",
    cena: 24,
    krajina: "",
    popis:
      "Finlandia vodka je čistá a dokonalá jediná prémiova vodka na svete,vyrobená z prírodnej filtrovanej ľadovcovej vody a šesťradého jačmeňa, dokonalevyzretého v arktickom lete. Používané suroviny nesmú byť vyrábané inde než voFínsku. Je mrazivo priezračná, zamatovo čistá, je vytvorená pre výnimočné chvíle. Red Bull je funkčný nápoj, ktorý vám dáva krídla, kedykoľvek ich potrebujete. KEDY HO PIŤ? Pri šoférovaní, v škole a počas štúdia, v práci, pri športe či hraní videohier alebo keď sa idete baviť - tak vo dne, ako aj v noci.",
  },
  {
    id: 43,
    produkt: "Finlandia Vodka 40% + Cappy pomaranc.dzus",
    typ: "Párty sety",
    objem: "0.7l + 1l",
    obsah: "40%",
    cena: 19,
    krajina: "",
    popis:
      "Finlandia vodka je čistá a dokonalá jediná prémiova vodka na svete,vyrobená z prírodnej filtrovanej ľadovcovej vody a šesťradého jačmeňa, dokonalevyzretého v arktickom lete. Používané suroviny nesmú byť vyrábané inde než voFínsku. Je mrazivo priezračná, zamatovo čistá, je vytvorená pre výnimočné chvíle. Kvalitné džúsy, nektáre a ovocné nápoje nájdete v obchodoch pod značkou Cappy. Sú vyrábané zo starostlivo vyberaného ovocia a neobsahujú farbivá ani konzervačné látky. Vďaka širokej ponuke príchutí v rôznych baleniach si z nich vyberie úplne každý.",
  },
  {
    id: 44,
    produkt: "Cappy Džús",
    typ: "Nealko",
    objem: "1l",
    obsah: "",
    cena: 3,
    krajina: "",
    popis:
      "Kvalitné džúsy, nektáre a ovocné nápoje nájdete v obchodoch pod značkou Cappy. Sú vyrábané zo starostlivo vyberaného ovocia a neobsahujú farbivá ani konzervačné látky. Vďaka širokej ponuke príchutí v rôznych baleniach si z nich vyberie úplne každý.",
  },
  {
    id: 45,
    produkt: "Kinley Tonic ružový",
    typ: "Nealko",
    objem: "1.75l",
    obsah: "",
    cena: 2,
    krajina: "",
    popis:
      "Charakter nápojov Kinley presahuje hranice krajiny a kultúry. Vďaka nemu zažiješ radosť z objavovania bez ohľadu na to, na akú cestu sa vydáš. Každý dúšok je jedinečný ako ty. Na zdravie!",
  },
  {
    id: 46,
    produkt: "Sprite",
    typ: "Nealko",
    objem: "1.75l",
    obsah: "",
    cena: 2,
    krajina: "",
    popis:
      "Sprite je štvrtým najobľúbenejším sýteným nealkoholickým nápojom na svete a vo svojej kategórii má na trhu poprednú pozíciu. Prvýkrát bol predstavený v roku 1961 v Spojených štátoch, teraz sa predáva vo viac než 190 krajinách, od roku 1991 vrátane Slovenskej republiky.",
  },
  {
    id: 47,
    produkt: "Coca Cola",
    typ: "Nealko",
    objem: "1.75l",
    obsah: "",
    cena: 2,
    krajina: "",
    popis:
      "Coca-Cola je osviežujúci nealkoholický nápoj, ktorý prináša okamžiky pohody a radosti viac ako 125 rokov.",
  },
  {
    id: 48,
    produkt: "Kinley Tonic",
    typ: "Nealko",
    objem: "1.75l",
    obsah: "",
    cena: 2,
    krajina: "",
    popis:
      "Charakter nápojov Kinley presahuje hranice krajiny a kultúry. Vďaka nemu zažiješ radosť z objavovania bez ohľadu na to, na akú cestu sa vydáš. Každý dúšok je jedinečný ako ty. Na zdravie!",
  },
  {
    id: 49,
    produkt: "Red Bull",
    typ: "Nealko",
    objem: "250ml",
    obsah: "",
    cena: 2,
    krajina: "",
    popis:
      "Red Bull je funkčný nápoj, ktorý vám dáva krídla, kedykoľvek ich potrebujete. KEDY HO PIŤ? Pri šoférovaní, v škole a počas štúdia, v práci, pri športe či hraní videohier alebo keď sa idete baviť - tak vo dne, ako aj v noci.",
  },
  {
    id: 50,
    produkt: "Rajec neperlivý",
    typ: "Nealko",
    objem: "1.5l",
    obsah: "",
    cena: 2,
    krajina: "",
    popis:
      "Pramenitá voda Rajec obsahuje vyvážené množstvo minerálov. Môžete si na nej ulietať každý deň.",
  },
  {
    id: 51,
    produkt: "Rajec jemne perlivý",
    typ: "Nealko",
    objem: "1.5l",
    obsah: "",
    cena: 2,
    krajina: "",
    popis:
      "Pramenitá voda Rajec obsahuje vyvážené množstvo minerálov. Môžete si na nej ulietať každý deň.",
  },
  {
    id: 52,
    produkt: "Hamšík Prosseco Treviso D.O.C. Extra Dry",
    typ: "Víno",
    objem: "0,75l",
    obsah: "11%",
    cena: 15,
    krajina: "Taliansko",
    popis:
      "Cuvée sa vyrába z odrody hrozna Glera pestovanej v najlepších oblastiach v provincii Treviso, kde enviromentálne a pôdne podmienky majú osobitné kvalitatívne vlastnosti. Víno má žiarivo žltú farbu so zelenkastými tónmi. Má nádhernú vôňu zrelých jabĺk a citrusových plodov. Chuť je svieža, ľahká a harmonická.",
  },
  {
    id: 53,
    produkt: "Beefeater Gin 40% + Kinley Tonic ružový",
    typ: "Párty sety",
    objem: "0.7l + 1.5l",
    obsah: "40%",
    cena: 23,
    krajina: "",
    popis:
      "Najoceňovanejší prémiový gin na svete. Beefeater je jediný gin, ktorý savyrába priamo v Londýne, čo z neho robí už desaťročia pravého britskéhogentlemana, ktorý po celom svete hrdo a patrične reprezentuje svoje rodisko.Beefeater je oviežujúci, čistý a zároveň ostrý gin s nepatrným nádychom citrusov aovocia, vyváženým chuťou korenia. Je výborným základom pre rôzne koktaily.Beefeater Gin je číslo jeden spomedzi prémiových ginov sveta a ročne sa ho predáviac ako 21 miliónov litrov. Charakter nápojov Kinley presahuje hranice krajiny a kultúry. Vďaka nemu zažiješ radosť z objavovania bez ohľadu na to, na akú cestu sa vydáš. Každý dúšok je jedinečný ako ty. Na zdravie!",
  },
  {
    id: 54,
    produkt:
      "Aperol Spritz 0.7l + Hamšík Prosecco Treviso DOC Extra Dry 0.75l + Rajec jemný 1.5l",
    typ: "Párty sety",
    objem: "0.7l + 0.75l + 1.5l",
    obsah: "11%",
    cena: 33,
    krajina: "",
    popis:
      "Aperol je alkoholický nápoj radiaci sa medzi korenené bittery. Má oranžovo-červenú farbu s ovocnou ľahkou horkou chuťou. Vyrába sa z horca, rebarbory, výťažkov z pomarančov, aromatických bylín a farbív. Vznikol v talianskej rodinnej firme Barbieri na kraji mesta Padova okolo roku 1919. Jeho zvláštnosťou je veľmi nízky obsah alkoholu. Šumivé víno s jemným svetložltým odtieňom, s pravidelným perlením, z odrody Glera. Aromatický výraz je stredne intenzívny, tvorený tónmi drobných bielych kvetov a doplnených notou zrelej letnej hrušky. V ústach je víno svieže a veľmi príjemné. V chuti dominuje tón zrelej mirabelky a bielej broskyne.",
  },
  {
    id: 55,
    produkt: "Tequilla Olmeca: Bianco",
    typ: "Tequilla",
    objem: "0,7l",
    obsah: "38%",
    cena: 23,
    krajina: "Mexiko",
    popis:
      "Tequilla Olmeca Bianco: Nádherná priezračná tequila vyrobená zo špičkovej modrej agávy a špeciálnym procesom, ktorý zdôrazňuje jej výnimočnú čistotu. Čistá najlepšie chutís citrónom a soľou, no je skvelá i na prípravu obľúbených drinkov ako TequilaSunrise alebo Margarita.",
  },
  {
    id: 56,
    produkt: "Ron Espero Creole Coconut",
    typ: "Rum",
    objem: "0,7l",
    obsah: "40%",
    cena: 30,
    krajina: "Dominikánska republika",
    popis:
      "Ron Espero Coconut & Rum z Dominikánskej republiky je ideálny pre každého, kto sa chce liečiť populárnym rumovým likérom s kokosovou príchuťou. Tento tmavý rumový likér kombinuje to najlepšie z mladého melasového dominikánskeho rumu s výdatnými prírodnými tónmi zrelých kokosových orechov.",
  },
  {
    id: 57,
    produkt: "Vodka Nicolaus Blackcurrant",
    typ: "Vodka",
    objem: "0,7l",
    obsah: "38%",
    cena: 13,
    krajina: "Slovensko",
    popis:
      "Extra jemná, prirodzená chuť a vôňa vodky z čiernych ríbezlí Vás očarí hneď pri prvom dúšku. Vyrobená je z krištáľovo čistej tatranskej vody a jemného obilného liehu. Pred finálnou úpravou bola filtrovaná cez unikátne strieborné filtre, ktoré jej dodali lahodnosť a čistotu.",
  },
  {
    id: 58,
    produkt: "Vodka Nicolaus Melon",
    typ: "Vodka",
    objem: "0,7l",
    obsah: "38%",
    cena: 13,
    krajina: "Slovensko",
    popis:
      "Extra jemná, prirodzená chuť a vôňa vodky z čiernych ríbezlí Vás očarí hneď pri prvom dúšku. Vyrobená je z krištáľovo čistej tatranskej vody a jemného obilného liehu. Pred finálnou úpravou bola filtrovaná cez unikátne strieborné filtre, ktoré jej dodali lahodnosť a čistotu.",
  },
  {
    id: 59,
    produkt: "Vodka Nicolaus Cranberry",
    typ: "Vodka",
    objem: "0,7l",
    obsah: "38%",
    cena: 13,
    krajina: "Slovensko",
    popis:
      "Extra jemná, prirodzená chuť a vôňa vodky z čiernych ríbezlí Vás očarí hneď pri prvom dúšku. Vyrobená je z krištáľovo čistej tatranskej vody a jemného obilného liehu. Pred finálnou úpravou bola filtrovaná cez unikátne strieborné filtre, ktoré jej dodali lahodnosť a čistotu.",
  },
  {
    id: 60,
    produkt: "Vodka Nicolaus Lime",
    typ: "Vodka",
    objem: "0,7l",
    obsah: "38%",
    cena: 13,
    krajina: "Slovensko",
    popis:
      "Extra jemná, prirodzená chuť a vôňa vodky z čiernych ríbezlí Vás očarí hneď pri prvom dúšku. Vyrobená je z krištáľovo čistej tatranskej vody a jemného obilného liehu. Pred finálnou úpravou bola filtrovaná cez unikátne strieborné filtre, ktoré jej dodali lahodnosť a čistotu.",
  },
  {
    id: 61,
    produkt: "Rum Božkov Republika",
    typ: "Rum",
    objem: "0,7l",
    obsah: "38%",
    cena: 18,
    krajina: "Česká Republika",
    popis:
      "Milovníci rumu a kvalitného alkoholu určite ocenia tento tmavý nápoj vyrobený z osemročných karibských rumov, citlivo dochutený trstinovým cukrom. Jeho jemná delikátna sladkastá chuť s príjemnými tónmi vanilky, sušeného ovocia a aromatických orieškov vás nesklame.",
  },
];

// instert ID 20
